### ISSUE TITLE
数据库在哪里

### ISSUE THREAD

**Issue by Comver** [YunYinORG/print#19]
请问数据库在哪里 没找到sql文件 也没看到自动安装的文件。

**Comment by Comver** [comment]
已经找到了。是单独的分支。

**Comment by New-Future** [comment]
不同数据库导进去可能有些区别，需要注意一下


NewFuture to You !

-------- 原始邮件 --------
发件人：Comver <notifications@github.com>
时间：周一 6月15日 01:54
收件人：YunYinORG/print <print@noreply.github.com>
主题：Re: [print] 数据库在哪里 (#19)
